for cleaning process we import the python libraries

In [1307]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import the data set

In [1308]:
RAW_DATA_PATH="../data/raw/Adidas_Synthetic_Messy_Data_Analytics_Project.xlsx"
df = pd.read_excel(
    RAW_DATA_PATH,
    sheet_name="Messy_Raw_Data"
)

copy the raw data for backup
deep=True kyun?
Yeh raw data ki independent copy banata hai.meand original data per koi effect nahi parta

In [1309]:
df_raw = df.copy(deep=True)

confirm the duplicate rows

In [1311]:
duplicate_count = df.duplicated().sum()
print(f"the duplicated rows are {duplicate_count}")

the duplicated rows are 45


remove the exact duplicated rows 

In [1312]:
rows_before = len(df)
print(f"rows_before length with duplicate rows {rows_before}")
df = df.drop_duplicates(keep="first").reset_index(drop=True)
rows_after = len(df)
print(f"rows after the  length without duplicate rows {rows_after}")

rows_before length with duplicate rows 3045
rows after the  length without duplicate rows 3000


In [1313]:
df.shape

(3000, 28)

text whitespacing removeing 

In [1314]:
text_columns = df.select_dtypes(
    include=["object", "string"]
).columns.tolist()
for col in text_columns:
    df[col] = df[col].str.strip()

country and sale channel standardization

In [1315]:
df["Country"]=(df["Country"].str.strip().str.title())
df['Sales_Channel']=(df['Sales_Channel'].str.strip().str.title())



invalid valuesin the numerical data type 
steps 
  1 >> range select
  2 >> convert it into the nan
  3 >> fill by  different methods like means ,median ,mode ,knn etc 

In [1316]:
df.loc[
    (df["Customer_Age"] < 13) |
    (df["Customer_Age"] > 100),
    "Customer_Age"
] = np.nan

df.loc[
    df["Shipping_Days"] < 0,
    "Shipping_Days"
] = np.nan

df.loc[
    (df["Discount_Rate"] < 0) |
    (df["Discount_Rate"] > 1),
    "Discount_Rate"
] = np.nan



In [1317]:
from sklearn.impute import KNNImputer
knn = KNNImputer(n_neighbors=5, weights="distance")

In [1318]:
knn_features = ["Customer_Age","Customer_Rating","Shipping_Days",
                "Discount_Rate","Marketing_Spend_USD","Quantity",
                "Unit_Price_USD","Revenue_USD","Cost_USD","Profit_USD"]
df[knn_features] = knn.fit_transform(
    df[knn_features])

In [1319]:
df[
    [
        "Customer_Age",
        "Customer_Rating",
        "Shipping_Days",
        "Discount_Rate",
        "Marketing_Spend_USD"
    ]
].describe()

,Customer_Age,Customer_Rating,Shipping_Days,Discount_Rate,Marketing_Spend_USD
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,41.561839,3.977904,4.042461,0.111262,50010.771989
std,13.185137,0.990751,3.615718,0.100545,28005.982080
min,18.000000,1.000000,0.000000,0.000000,509.310000
25%,31.000000,3.615570,2.949828,0.050000,26100.510522
50%,41.978835,4.000000,3.278493,0.100000,50011.409400
75%,53.000000,5.000000,5.000000,0.150000,74004.775000
max,64.000000,5.000000,90.000000,0.500000,99995.720000


In [1320]:
missing_percentage = (df.isnull().sum()/ len(df)) * 100

missing_report = pd.DataFrame({
    "Missing_Values": df.isnull().sum(),
    "Missing_Percentage": missing_percentage
})

missing_report[
    missing_report["Missing_Values"] > 0].sort_values(by="Missing_Percentage",ascending=False)

,Missing_Values,Missing_Percentage
Campaign,714,23.8
City,240,8.0
Size,210,7.0
Gender,180,6.0


changing the data type of custumer age,custumer rating ,shiping days

In [1321]:
df['Customer_Rating'].unique()

array([5.        , 3.        , 4.        , 2.        , 3.11200179,
       4.77376737, 4.36141925, 3.85905668, 3.68992611, 3.98998058,
       1.        , 4.44928141, 4.05299944, 4.07433708, 3.53567358,
       3.99096324, 3.58967968, 4.05623289, 4.26927087, 4.08341556,
       4.6188944 , 4.41356833, 2.99811144, 4.23769182, 3.68999966,
       3.7988798 , 4.49902812, 3.6439808 , 3.34200965, 3.69404636,
       4.03560742, 3.06340618, 4.35504937, 3.87165024, 4.08044736,
       4.28840256, 4.40372669, 3.83993292, 4.47096089, 3.19239749,
       4.57474384, 4.59202348, 3.72041777, 3.9520629 , 3.76615946,
       3.2307636 , 3.88060952, 4.05389009, 4.13396928, 4.1000506 ,
       3.91472407, 3.73298491, 2.88119239, 4.26111293, 3.98320425,
       4.30085217, 3.8150506 , 4.11654735, 4.17443516, 4.2387681 ,
       4.02054985, 4.51151268, 3.19952254, 3.73828107, 4.64864639,
       4.19949316, 3.45765191, 3.80770528, 3.40568933, 3.99855577,
       3.58471234, 3.69841188, 3.90928012, 4.18404386, 3.53464

changing the customer age,customer rating,shipping days  columns ki data type changes

In [1322]:
df['Customer_Age']=df['Customer_Age'].astype(int)
df['Customer_Rating']=df['Customer_Rating'].astype(int)
df['Shipping_Days']=df['Shipping_Days'].astype(int)

In [1323]:
df['Customer_Age'].unique()

array([40, 64, 37, 43, 62, 58, 18, 47, 54, 34, 24, 63, 39, 21, 38, 19, 57,
       42, 33, 45, 29, 28, 46, 36, 56, 53, 25, 20, 30, 55, 23, 48, 31, 59,
       22, 32, 44, 51, 41, 26, 49, 61, 52, 35, 27, 60, 50])

In [1324]:
df['Discount_Rate'].unique()

array([0.2       , 0.05      , 0.        , 0.15      , 0.3       ,
       0.12591379, 0.1       , 0.5       , 0.03910769, 0.22433474,
       0.06881769, 0.11082096, 0.0582202 , 0.06278006, 0.07316601,
       0.08153544, 0.06060182, 0.0647134 , 0.0932597 , 0.0700722 ,
       0.06910081, 0.08676056, 0.11561709, 0.15      , 0.12758311,
       0.11466267, 0.1124561 , 0.09540278, 0.01716837, 0.18012852,
       0.04175135, 0.07315043, 0.11783694, 0.0180721 , 0.14918718,
       0.15404937, 0.07419826, 0.14977258, 0.0995158 , 0.07113023,
       0.06020728, 0.07222529, 0.14770747, 0.06319169, 0.14632533,
       0.06791825, 0.11987732, 0.11228155, 0.08405565, 0.03265157,
       0.04412094, 0.11810434, 0.12729222, 0.07011096, 0.09134382,
       0.06284552, 0.11707546, 0.06614858, 0.07178847, 0.12091178,
       0.28829829, 0.13541523, 0.1173182 , 0.15939545, 0.04313827,
       0.1019582 , 0.05875725, 0.12345205, 0.06662503, 0.01876099,
       0.10443371, 0.15875952, 0.12963239, 0.05666747, 0.11073

In [1325]:
df['Discount_Rate'] = (df['Discount_Rate'] * 100).round(2)

In [1326]:
df['Discount_Rate'].unique()

array([20.  ,  5.  ,  0.  , 15.  , 30.  , 12.59, 10.  , 50.  ,  3.91,
       22.43,  6.88, 11.08,  5.82,  6.28,  7.32,  8.15,  6.06,  6.47,
        9.33,  7.01,  6.91,  8.68, 11.56, 12.76, 11.47, 11.25,  9.54,
        1.72, 18.01,  4.18, 11.78,  1.81, 14.92, 15.4 ,  7.42, 14.98,
        9.95,  7.11,  6.02,  7.22, 14.77,  6.32, 14.63,  6.79, 11.99,
       11.23,  8.41,  3.27,  4.41, 11.81, 12.73,  9.13, 11.71,  6.61,
        7.18, 12.09, 28.83, 13.54, 11.73, 15.94,  4.31, 10.2 ,  5.88,
       12.35,  6.66,  1.88, 10.44, 15.88, 12.96,  5.67, 11.07, 15.06,
       15.97,  8.64,  4.3 , 23.1 , 17.36,  4.07,  8.51, 13.43,  8.69,
       10.94, 18.97, 13.2 ,  9.11, 11.83, 16.84, 13.7 ,  1.14,  5.89,
        3.55, 15.04, 14.91, 10.3 ,  9.75, 13.24,  6.62, 12.49, 12.64,
        7.92, 31.74, 13.51, 13.87, 14.31, 14.96,  6.99, 10.79,  9.37,
        8.02,  9.68,  7.45, 10.16, 15.86,  8.04,  4.81, 12.33, 10.68,
        7.37, 29.38,  7.36,  6.55, 13.77, 12.03,  2.27,  7.66,  9.19,
        9.89, 14.35,

In [1327]:
df['Marketing_Spend_USD'].unique()
df['Marketing_Spend_USD'].dtypes

dtype('float64')

remaning missing values of categorical data handle

In [1328]:
remaining_missing = pd.DataFrame({
""
    "Missing_Count": df.isnull().sum(),

    "Missing_%":
    round(df.isnull().mean()*100,2)
})
remaining_missing = remaining_missing[
    remaining_missing["Missing_Count"]>0
]
remaining_missing

,Missing_Count,Missing_%
City,240,8.0
Gender,180,6.0
Size,210,7.0
Campaign,714,23.8


In [1329]:
invalid = ["?","Unknown","N/A","None"]
df["Gender"] = df["Gender"].replace(invalid, np.nan)

In [1330]:
df['Gender'].isna().sum()

np.int64(180)

In [1331]:
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])

In [1332]:
df['City'].unique()

array(['Mumbai', 'Karachi', 'Riyadh', 'Berlin', 'Sydney', 'Delhi', nan,
       'Jeddah', 'Melbourne', 'Los Angeles', 'Sharjah', 'Birmingham',
       'Dammam', 'Abu Dhabi', 'Lahore', 'Chennai', 'Faisalabad',
       'Rawalpindi', 'London', 'Dubai', 'Manchester', 'Houston',
       'Hamburg', 'Chicago', 'Kolkata', 'Munich', 'Bangalore', 'Brisbane',
       'New York', 'Islamabad'], dtype=object)

In [1333]:
df["City"] = (
    df.groupby("Country")["City"]
      .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else np.nan))
)

In [1334]:
df['Size'].unique()

array(['S', 'XS', '43', '42', 'XL', '45', 'L', nan, '44', 'M'],
      dtype=object)

In [1335]:
size_mode = df["Size"].mode()[0]
df["Size"] = df["Size"].fillna(size_mode)

In [1336]:
df['Size'].unique()

array(['S', 'XS', '43', '42', 'XL', '45', 'L', '44', 'M'], dtype=object)

In [1337]:
size_map = {
    "XS": 36,
    "S": 38,
    "M": 40,
    "L": 42,
    "XL": 44
}
df["Size"] = df["Size"].replace(size_map)
df["Size"] = pd.to_numeric(df["Size"], errors="coerce")

In [1338]:
df["Campaign"].unique()

array(['Eid Campaign', 'Summer Sale', 'Sports Event', 'New Year Sale',
       nan, 'Black Friday'], dtype=object)

In [1339]:
df["Campaign"] = df["Campaign"].fillna("No Campaign")

In [1340]:
missing_percentage = (df.isnull().sum()/ len(df)) * 100
missing_report = pd.DataFrame({
    "Missing_Values": df.isnull().sum(),
    "Missing_Percentage": missing_percentage})
missing_report[
    missing_report["Missing_Values"] > 0].sort_values(by="Missing_Percentage",ascending=False)

,Missing_Values,Missing_Percentage


In [1341]:
df['Revenue_USD'].unique()

array([170.09, 193.52, 134.59, ...,  59.77,  38.27, 308.18], shape=(2756,))

In [1342]:
df.to_csv(
    "adidas_cleaned_dataset.csv",
    index=False
)

In [1343]:
clean_data=pd.read_csv("../notebooks/adidas_cleaned_dataset.csv")
clean_data.sample(5)

,Order_ID,Order_Date,Customer_ID,Country,Region,City,Category,Product,Gender,Size,...,Cost_USD,Profit_USD,Customer_Rating,Returned,Order_Status,Customer_Age,Shipping_Days,Inventory_Available,Marketing_Spend_USD,Customer_Lifetime_Value_USD
997,ORD-100997,1970-01-01 05:00:45.015,CUST-10133,India,South Asia,Kolkata,Basketball,D.O.N. Issue,Male,40,...,83.35,36.84,3,No,Completed,24,4,385,37917.890815,3274.73
1032,ORD-101032,1970-01-01 05:00:45.756,CUST-10521,Uae,Middle East,Dubai,Running,Solarboost,Female,44,...,81.49,106.41,5,No,Completed,46,3,413,2097.690000,1786.33
800,ORD-100800,1970-01-01 05:00:45.198,CUST-10315,Germany,Europe,Berlin,Training,Rapidmove,Unisex,44,...,67.94,39.16,3,No,Completed,42,1,9,42460.460000,4911.28
1343,ORD-101343,1970-01-01 05:00:45.628,CUST-10497,Australia,Oceania,Brisbane,Outdoor,Terrex,Female,38,...,126.64,101.36,5,No,Completed,49,3,121,8980.420000,1193.29
289,ORD-100289,1970-01-01 05:00:45.118,CUST-10007,Uk,Europe,Birmingham,Football,Copa,Female,44,...,72.68,31.37,5,No,Completed,64,3,737,94838.320000,3504.90
